name: Validate code

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Typescript check and lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20, 22]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup using Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Typescript reviewdog check
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          # Change reviewdog reporter if you need
          # [github-pr-check,github-check,github-pr-review].
          # More about reviewdog reporters at
          # https://github.com/reviewdog/reviewdog#reporters
          reporter: github-check
          # Change reporter level if you need
          # [info,warning,error].
          # More about reviewdog reporter level at
          # https://github.com/reviewdog/reviewdog#reporters
          level: warning
      - name: Typescript check
        run: npm run typecheck
      - name: ESlint check
        run: npm run lint

      # Tests require internal network - until we have GINIS mocked for ci we're omitting
      # - name: Tests
      #   run: npm run test:ci
